CREATE DATABASE Academy;
GO;
USE Academy;

CREATE TABLE  GROUPS(
    ID INT PRIMARY KEY IDENTITY (1,1),
    NAME NCHAR(10) NOT NULL UNIQUE,
    RATING INT NOT NULL CHECK (Rating >= 0 and Rating <= 5),
    YEAR INT NOT NULL CHECK(YEAR >= 1 AND YEAR <= 5)
)

CREATE TABLE DEPARTMENTS(
    ID INT PRIMARY KEY IDENTITY (1,1),
    FINANCING MONEY NOT NULL CHECK (FINANCING >= 0) DEFAULT (0),
    NAME NVARCHAR(100) NOT NULL UNIQUE CHECK(Name <> ''),
)


CREATE TABLE FACULTIES (
   ID INT PRIMARY KEY IDENTITY (1, 1),
   NAME NVARCHAR(100) NOT NULL UNIQUE CHECK(NAME <> ' ')
)

CREATE TABLE TEACHERS (
    ID INT PRIMARY KEY IDENTITY (1, 1),
    EMPLOYMENTDATE DATE NOT NULL CHECK(EMPLOYMENTDATE > '01.01.1990'),
    NAME NVARCHAR(100) NOT NULL UNIQUE CHECK(NAME <> ' '),
    PREMIUM MONEY NOT NULL CHECK(PREMIUM >= 0) DEFAULT(0),
    SALARY MONEY NOT NULL CHECK(SALARY > 0),
    SURNAME NVARCHAR(MAX) NOT NULL CHECK(SURNAME <> ' '),
)